version: '3.8'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app  # Nginx should wait for FastAPI
