version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi
